---
- name: Set _kube_vip_bgp_peers fact
  ansible.builtin.set_fact:
    _kube_vip_bgp_peers: "{{ lookup('community.general.merge_variables', '^kube_vip_bgp_peers__.+$', initial_value=kube_vip_bgp_peers, groups=kube_vip_bgp_peers_groups) }}"  # yamllint disable-line rule:line-length

- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /mnt/k3s/etcd/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Download vip rbac manifest to first master
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: /mnt/k3s/etcd/server/manifests/vip-rbac.yaml
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Copy vip manifest to first master
  ansible.builtin.template:
    src: vip.yaml.j2
    dest: /mnt/k3s/etcd/server/manifests/vip.yaml
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
